DROP INDEX street_name_unique_idx IF EXISTS;
DROP TABLE bf_address IF EXISTS;
DROP TABLE bf_postman IF EXISTS;
DROP TABLE bf_area IF EXISTS;
DROP TABLE bf_phone IF EXISTS;
DROP TABLE bf_house IF EXISTS;
DROP TABLE bf_street IF EXISTS;
DROP TABLE bf_district IF EXISTS;
DROP TABLE bf_city IF EXISTS;
DROP TABLE bf_region IF EXISTS;
DROP TABLE bf_subscriber IF EXISTS;


CREATE TABLE bf_region
(
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  UNIQUE (name)
);

CREATE TABLE bf_city
(
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  name      VARCHAR(255) NOT NULL,
  region_id INT          NOT NULL,
  FOREIGN KEY (region_id) REFERENCES bf_region (id)
    ON DELETE CASCADE,
  CONSTRAINT name_region_city_idx UNIQUE (name, region_id),
  UNIQUE (name)
);

CREATE TABLE bf_district
(
  id      INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  name    VARCHAR(255) NOT NULL,
  city_id INT          NOT NULL,
  FOREIGN KEY (city_id) REFERENCES bf_city (id)
    ON DELETE CASCADE,
  CONSTRAINT name_city_district_idx UNIQUE (name, city_id),
  UNIQUE (name)
);

CREATE TABLE bf_street
(
  id      INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  name    VARCHAR(255) NOT NULL,
  city_id INT          NOT NULL,
  FOREIGN KEY (city_id) REFERENCES bf_city (id)
    ON DELETE CASCADE,
  CONSTRAINT name_city_street_idx UNIQUE (name, city_id),
  UNIQUE (name)
);

CREATE TABLE bf_subscriber
(
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  lastname      VARCHAR(50),
  firstname     VARCHAR(50),
  middlename    VARCHAR(50),
  birthday      DATE,
  subscribe_day DATE,
  status        VARCHAR(255)
);

CREATE TABLE bf_house
(
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  street_id    INT NOT NULL,
  house        VARCHAR(20) NOT NULL,
  corps        VARCHAR(20),
  corps_letter VARCHAR(10),
  FOREIGN KEY (street_id) REFERENCES bf_street (id) ON DELETE CASCADE,
  CONSTRAINT street_house_corps_letter_idx UNIQUE (street_id, house, corps, corps_letter)
);

CREATE TABLE bf_area
(
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  city_id     INT NOT NULL,
  FOREIGN KEY (city_id) REFERENCES bf_city (id) ON DELETE CASCADE,
  CONSTRAINT name_city_area_idx UNIQUE (name, city_id),
  UNIQUE (name)
);

CREATE TABLE bf_postman
(
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  area_id     INT NOT NULL,
  FOREIGN KEY (area_id) REFERENCES bf_area (id) ON DELETE CASCADE,
  CONSTRAINT name_area_postman_idx UNIQUE (name, area_id),
  UNIQUE (name)
);

CREATE TABLE bf_address
(
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
--   area_id       INTEGER DEFAULT NULL,
  sector        VARCHAR(20),
  mail_index    VARCHAR(20),
  region_id     INT NOT NULL,
  city_id       INT NOT NULL,
  district_id   INT NOT NULL,
  house_id      INT NOT NULL,
  flat          VARCHAR(20),
  subscriber_id INT NOT NULL,
  FOREIGN KEY (region_id) REFERENCES bf_region (id) ON DELETE CASCADE,
  FOREIGN KEY (city_id) REFERENCES bf_city (id) ON DELETE CASCADE,
  FOREIGN KEY (district_id) REFERENCES bf_district (id) ON DELETE CASCADE,
  FOREIGN KEY (house_id) REFERENCES bf_house (id) ON DELETE CASCADE,
--   FOREIGN KEY (area_id) REFERENCES bf_area (id) ON DELETE CASCADE,
  FOREIGN KEY (subscriber_id) REFERENCES bf_subscriber (id)
    ON DELETE CASCADE
);

CREATE TABLE bf_phone
(
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  cellPhone     VARCHAR(100),
  home_phone    VARCHAR(100),
  subscriber_id INT NOT NULL,
  FOREIGN KEY (subscriber_id) REFERENCES bf_subscriber (id)
    ON DELETE CASCADE
);










